complete the challenge
yasirelbouazzati/JavaScript-functions pull request #1
Opened 2023-11-19 16:10 UTC by yasirelbouazzati

i complete the all tasks of the challenge

2023-11-19 20:11 UTC, tictools requested changes

2023-11-19 20:11 UTC, tictools commented on .DS_Store
FIX: add `.DS_Store` to `.gitignore` and remove this file

2023-11-19 20:11 UTC, tictools commented on exercise_01/getDistanceFromThreshold.js
Comment was defining the name of the params (value, threshold)

```js
/**
* #1 :: ...
 * input: number (value) 👈
 * input: number (threshold) 👈
 * output: number
 */
```
FIX: rename params

2023-11-19 20:11 UTC, tictools commented on exercise_01/index.js
FIX: rename argument `value_2`

2023-11-19 20:11 UTC, tictools commented on exercise_02/getTotalWordsFromString.js
> +  const totalWords = words.filter((word) => word !== "").length;
Do you understand what you are doing here? How does `filter` work?... 🤔
We haven't still worked with array methods.

2023-11-20 18:20 UTC, AGUACATE2304 commented on index.html
Project Requirements didn't asked to create this file.

2023-11-20 18:28 UTC, AGUACATE2304 commented on exercise_03/generateRandomNumberInRange.js
IMHO You should changes this.
const getTotalWordsFromString = (limit) {
 "Rest of code"
}
export default generateRandomNumberInRange;

2023-11-20 18:32 UTC, AGUACATE2304 commented on .gitignore
> +node_modules
Add blank line at end of the file.

2023-11-20 18:32 UTC, AGUACATE2304 commented on .prettierignore
Add blank line at end of the file.

2023-11-20 18:55 UTC, AGUACATE2304 requested changes
You need to change repo name.

05_JavaScript_functions    >    Javascript-functions

2023-11-20 18:55 UTC, AGUACATE2304 commented on exercise_04/isGreaterThan.js
IMHO You should changes this.
const isGreaterThan = (value, threshold) {
"Rest of code"
}
export default isGreaterThan;

2023-11-20 18:55 UTC, AGUACATE2304 commented on exercise_05/index.js
> +const number1 = 30;
Rename variable name  firstNumber

2023-11-20 18:55 UTC, AGUACATE2304 commented on exercise_05/index.js
> +const number2 = 25;
Rename variable name secondNumber

Use more concret varaible names

2023-11-20 18:55 UTC, AGUACATE2304 commented on exercise_07/isTypeOf.js
> +  } else {
Did you used chalistenics.

Don't do else

2023-11-20 18:55 UTC, AGUACATE2304 commented on package.json
>    },
Did you create GitHub Actions??

Add script:
"lint:fix": "npx prettier . --write"

2023-11-21 19:10 UTC, tictools approved these changes

2023-11-21 19:12 UTC, AGUACATE2304 approved these changes

2023-11-21 19:15 UTC, merged